# Generated by Django 3.2.8 on 2021-11-15 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_num', models.AutoField(primary_key=True, serialize=False)),
                ('menu_catenum', models.IntegerField()),
                ('menu_name2', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Prefer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_num', models.IntegerField()),
                ('pref_menu', models.IntegerField()),
                ('pref_like', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rest',
            fields=[
                ('rest_num', models.AutoField(primary_key=True, serialize=False)),
                ('rest_name', models.CharField(max_length=30)),
                ('rest_star', models.FloatField(default=5)),
                ('rest_location_lat', models.FloatField(default=0)),
                ('rest_location_lon', models.FloatField(default=0)),
                ('rest_recent_user', models.IntegerField(default=0)),
                ('rest_number_reviews', models.IntegerField(default=0)),
                ('rest_distance_fromBD', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_num', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=30)),
                ('nickname', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RestMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rest_menu', models.CharField(max_length=30)),
                ('price', models.IntegerField(default=0)),
                ('recommendmenu', models.FloatField(default=0)),
                ('rest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bootrc.rest')),
            ],
        ),
    ]
