# Generated by Django 3.2.8 on 2021-11-22 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bootrc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rest',
            name='back_image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_back_image'),
        ),
        migrations.AddField(
            model_name='rest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_image'),
        ),
        migrations.AddField(
            model_name='restmenu',
            name='image',
            field=models.ImageField(blank=True, max_length=400, null=True, upload_to='menu_image'),
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('rest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='bootrc.rest')),
            ],
        ),
    ]
