# Generated by Django 3.2.8 on 2021-11-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootrc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rest',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='rest',
            name='closing_time',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='rest',
            name='opening_time',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='rest',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
    ]
