# Generated by Django 3.2.8 on 2021-11-23 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bootrc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='recentRecommended',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=300)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('menu_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bootrc.restmenu')),
                ('rest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_recommended', to='bootrc.rest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
