# Generated by Django 3.2.8 on 2021-11-16 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bootrc', '0002_auto_20211116_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prefer',
            name='pref_menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bootrc.menu'),
        ),
    ]
