# Generated by Django 3.2.8 on 2021-11-23 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bootrc', '0002_recentrecommended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentrecommended',
            name='comment',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.CreateModel(
            name='AppReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(default='', max_length=300)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('menu_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bootrc.restmenu')),
                ('rest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_review', to='bootrc.rest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
