# Generated by Django 3.2.8 on 2021-10-31 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootrc', '0002_alter_restmenu_rest_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restmenu',
            name='rest_menu',
            field=models.CharField(max_length=30),
        ),
    ]
