# Generated by Django 3.2.8 on 2021-11-01 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bootrc', '0003_alter_restmenu_rest_menu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restmenu',
            old_name='rest_num',
            new_name='rest',
        ),
    ]
