# Generated by Django 3.2.8 on 2021-11-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootrc', '0004_rename_rest_num_restmenu_rest'),
    ]

    operations = [
        migrations.AddField(
            model_name='rest',
            name='rest_star',
            field=models.FloatField(default=5),
        ),
    ]
