# Generated by Django 3.2.8 on 2021-11-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootrc', '0004_prefercate'),
    ]

    operations = [
        migrations.AddField(
            model_name='rest',
            name='rank_data',
            field=models.IntegerField(default=0),
        ),
    ]
