# Generated by Django 3.2.8 on 2021-11-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootrc', '0005_rest_rank_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rest',
            name='rank_data',
            field=models.FloatField(default=0.0),
        ),
    ]
