# Generated by Django 3.2.8 on 2021-11-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootrc', '0005_rest_rest_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='rest',
            name='rest_location_lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rest',
            name='rest_location_lon',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rest',
            name='rest_number_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rest',
            name='rest_recent_user',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restmenu',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
