# Generated by Django 3.1.3 on 2021-11-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootrc', '0006_auto_20211104_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prefer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='restmenu',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
