# Generated by Django 3.2.8 on 2021-11-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootrc', '0008_auto_20211109_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='rest',
            name='rest_distance_fromBD',
            field=models.IntegerField(default=0),
        ),
    ]
