# Generated by Django 3.2.8 on 2021-11-12 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bootrc', '0009_rest_rest_distance_frombd'),
        ('bootrc', '0009_restmenu_recommendmenu'),
    ]

    operations = [
    ]
