# Generated by Django 3.2.8 on 2021-10-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_num', models.AutoField(primary_key=True, serialize=False)),
                ('menu_catenum', models.IntegerField()),
                ('menu_name2', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'menu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prefer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_num', models.IntegerField()),
                ('pref_menu', models.IntegerField()),
                ('pref_mod', models.IntegerField()),
            ],
            options={
                'db_table': 'prefer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rest',
            fields=[
                ('rest_num', models.AutoField(primary_key=True, serialize=False)),
                ('rest_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'rest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RestMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rest_num', models.IntegerField()),
                ('rest_menu', models.IntegerField()),
            ],
            options={
                'db_table': 'rest_menu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_num', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=30)),
                ('nickname', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
